# Design Mode Docker Compose for DevMorph Studio
# This configuration is optimized for design work with frontend tools and preview services

services:
  # Design-focused app service with frontend tools
  design:
    build:
      context: .
      dockerfile: Dockerfile.design
    environment:
      - APP_ENV=design
      - NODE_ENV=development
      - DESIGN_MODE=true
      - DEV_TOOLS_ENABLED=true
    volumes:
      - .:/app
      - design_node_modules:/app/node_modules
      - ./src:/app/src
      - ./assets:/app/assets
    ports:
      - "${DESIGN_PORT:-3001}:3001"  # Separate port for design mode
      - "3002:3002"  # For design tools like Storybook
    stdin_open: true
    tty: true
    networks:
      - devmorph

  # Design assets server
  assets:
    image: node:18-alpine
    working_dir: /app
    command: >
      sh -c "
        npm install -g live-server &&
        live-server --port=3003 --host=0.0.0.0 --watch=assets --open=/assets
      "
    volumes:
      - .:/app
    ports:
      - "3003:3003"
    networks:
      - devmorph

  # Design tooling service (e.g., Storybook, Figma integration)
  design-tools:
    build:
      context: .
      dockerfile: Dockerfile.design-tools
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - design_tools_node_modules:/app/node_modules
    ports:
      - "6006:6006"  # Storybook port
      - "9009:9009"  # Design system tools
    networks:
      - devmorph

  # Optional: Image optimization service for design assets
  image-optimizer:
    image: node:18-alpine
    working_dir: /app
    command: >
      sh -c "
        npm install -g imagemin-cli &&
        while inotifyd -c 'echo \"File changed\"' /app/assets/; do
          echo \"Optimizing images...\";
          imagemin /app/assets/**/*.{jpg,png,gif,webp} --out-dir=/app/assets/optimized
        done
      "
    volumes:
      - .:/app
    depends_on:
      - design
    networks:
      - devmorph

networks:
  devmorph:
    driver: bridge

volumes:
  design_node_modules:
  design_tools_node_modules: